//      /obj/daemon/terminal_d.c
//      from the Nightmare Mudlib
//      Contains all the terminal information used to initialize
//      a player's terminal settings
//      created by Pinkfish@Discworld
//      rewritten for the Nightmare Mudlib by Descartes of Borg 930903

#define ANSI(p) sprintf("%c["+(p)+"m", 27)
#define ANSI2(p) sprintf("%c[38;5;"+(p)+"m", 27)
#define ESC(p) sprintf("%c"+(p), 27)

nosave mapping term_info;

void create() {
    term_info = ([ "dumb":
                   ([ "RESET": "",
                      "BOLD": "",
                      "ULINE": "",
                      "FLASH":"",
                      "BLACK":"",
                      "RED":"",
                      "BLUE":"",
                      "CYAN":"",
                      "MAGENTA":"",
                      "ORANGE":"",
                      "YELLOW":"",
                      "GREEN":"",
                      "WHITE":"",
                      "BLACK":"",
                      "B_RED":"",
                      "B_ORANGE":"",
                      "B_YELLOW":"",
                      "B_BLACK":"",
                      "B_CYAN":"",
                      "B_WHITE":"",
                      "B_GREEN":"",
                      "B_BLUE":"",
                      "B_MAGENTA":"",
                      "C090":"",
                      "C091":"",
                      "C092":"",
                      "C093":"",
                      "C094":"",
                      "C095":"",
                      "C096":"",
                      "C097":"",
                      "C098":"",
                      "C099":"",
                      "C100":"",
                      "C101":"",
                      "C102":"",
                      "C103":"",
                      "C104":"",
                      "C105":"",
                      "C106":"",
                      "C107":"",
                      "C108":"",
                      "C109":"",
                      "C110":"",
                      "STATUS":"",
                      "WINDOW":"",
                      "INITTERM": "",
                      "ENDTERM":""]),
                   "ansi":
                   ([ "RESET":ANSI("0;37;40"),
                      "BOLD":ANSI(1),
                      "ULINE":ANSI(4),
                      "FLASH":ANSI(5),
                      "BLACK":ANSI(30),
                      "RED":ANSI(31),
                      "GREEN":ANSI(32),
                      "ORANGE":ANSI(33),
                      "YELLOW":ANSI(1)+ANSI(33),
                      "BLUE": ANSI(34),
                      "CYAN":ANSI(36),
                      "MAGENTA":ANSI(35),
                      "BLACK":ANSI(30),
                      "WHITE": ANSI(37),
                      "B_RED":ANSI(41),
                      "B_GREEN":ANSI(42),
                      "B_ORANGE":ANSI(43),
                      "B_YELLOW":ANSI(1)+ANSI(43),
                      "B_BLUE":ANSI(44),
                      "B_CYAN":ANSI(46),
                      "B_BLACK":ANSI(40),
                      "B_WHITE": ANSI(47),
                      "B_MAGENTA":ANSI(45),
                      "C090":ANSI2(90),
                      "C091":ANSI2(91),
                      "C092":ANSI2(92),
                      "C093":ANSI2(93),
                      "C094":ANSI2(94),
                      "C095":ANSI2(95),
                      "C096":ANSI2(96),
                      "C097":ANSI2(97),
                      "C098":ANSI2(98),
                      "C099":ANSI2(99),
                      "C100":ANSI2(100),
                      "C101":ANSI2(101),
                      "C102":ANSI2(102),
                      "C103":ANSI2(103),
                      "C104":ANSI2(104),
                      "C105":ANSI2(105),
                      "C106":ANSI2(106),
                      "C107":ANSI2(107),
                      "C108":ANSI2(108),
                      "C109":ANSI2(109),
                      "C110":ANSI2(110),
                      "STATUS":"",
                      "WINDOW":"",
                      "INITTERM":"",
                      "ENDTERM":"" ]),
                   "ansi-no-black":
                   ([ "RESET":ANSI("0;37;40"),
                      "BOLD":ANSI(1),
                      "ULINE":ANSI(4),
                      "FLASH":ANSI(5),
                      "BLACK":ANSI(34),
                      "RED":ANSI(31),
                      "GREEN":ANSI(32),
                      "ORANGE":ANSI(33),
                      "YELLOW":ANSI(1)+ANSI(33),
                      "BLUE": ANSI(34),
                      "CYAN":ANSI(36),
                      "MAGENTA":ANSI(35),
                      "BLACK":ANSI(34),
                      "WHITE": ANSI(37),
                      "B_RED":ANSI(41),
                      "B_GREEN":ANSI(42),
                      "B_ORANGE":ANSI(43),
                      "B_YELLOW":ANSI(1)+ANSI(43),
                      "B_BLUE":ANSI(44),
                      "B_CYAN":ANSI(46),
                      "B_BLACK":"",
                      "B_WHITE": ANSI(47),
                      "B_MAGENTA":ANSI(45),
                      "C090":ANSI2(90),
                      "C091":ANSI2(91),
                      "C092":ANSI2(92),
                      "C093":ANSI2(93),
                      "C094":ANSI2(94),
                      "C095":ANSI2(95),
                      "C096":ANSI2(96),
                      "C097":ANSI2(97),
                      "C098":ANSI2(98),
                      "C099":ANSI2(99),
                      "C100":ANSI2(100),
                      "C101":ANSI2(101),
                      "C102":ANSI2(102),
                      "C103":ANSI2(103),
                      "C104":ANSI2(104),
                      "C105":ANSI2(105),
                      "C106":ANSI2(106),
                      "C107":ANSI2(107),
                      "C108":ANSI2(108),
                      "C109":ANSI2(109),
                      "C110":ANSI2(110),
                      "STATUS":"",
                      "WINDOW":"",
                      "INITTERM":"",
                      "ENDTERM":"" ]),
                   "ansi-no-bgcolors":
                   ([ "RESET":ANSI("0;37;40"),
                      "BOLD":ANSI(1),
                      "ULINE":ANSI(4),
                      "FLASH":ANSI(5),
                      "BLACK":ANSI(30),
                      "RED":ANSI(31),
                      "GREEN":ANSI(32),
                      "ORANGE":ANSI(33),
                      "YELLOW":ANSI(1)+ANSI(33),
                      "BLUE": ANSI(34),
                      "CYAN":ANSI(36),
                      "MAGENTA":ANSI(35),
                      "BLACK":ANSI(30),
                      "WHITE": ANSI(37),
                      "B_RED":"",
                      "B_GREEN":"",
                      "B_ORANGE":"",
                      "B_YELLOW":"",
                      "B_BLUE":"",
                      "B_CYAN":"",
                      "B_BLACK":"",
                      "B_WHITE": "",
                      "B_MAGENTA":"",
                      "C090":ANSI2(90),
                      "C091":ANSI2(91),
                      "C092":ANSI2(92),
                      "C093":ANSI2(93),
                      "C094":ANSI2(94),
                      "C095":ANSI2(95),
                      "C096":ANSI2(96),
                      "C097":ANSI2(97),
                      "C098":ANSI2(98),
                      "C099":ANSI2(99),
                      "C100":ANSI2(100),
                      "C101":ANSI2(101),
                      "C102":ANSI2(102),
                      "C103":ANSI2(103),
                      "C104":ANSI2(104),
                      "C105":ANSI2(105),
                      "C106":ANSI2(106),
                      "C107":ANSI2(107),
                      "C108":ANSI2(108),
                      "C109":ANSI2(109),
                      "C110":ANSI2(110),
                      "STATUS":"",
                      "WINDOW":"",
                      "INITTERM":"",
                      "ENDTERM":"" ]),
                   "ansi-no-bg-no-black":
                   ([ "RESET":ANSI("0;37;40"),
                      "BOLD":ANSI(1),
                      "ULINE":ANSI(4),
                      "FLASH":ANSI(5),
                      "BLACK":ANSI(30),
                      "RED":ANSI(31),
                      "GREEN":ANSI(32),
                      "ORANGE":ANSI(33),
                      "YELLOW":ANSI(1)+ANSI(33),
                      "BLUE": ANSI(34),
                      "CYAN":ANSI(36),
                      "MAGENTA":ANSI(35),
                      "BLACK":ANSI(34),
                      "WHITE": ANSI(37),
                      "B_RED":"",
                      "B_GREEN":"",
                      "B_ORANGE":"",
                      "B_YELLOW":"",
                      "B_BLUE":"",
                      "B_CYAN":"",
                      "B_BLACK":"",
                      "B_WHITE": "",
                      "B_MAGENTA":"",
                      "C090":ANSI2(90),
                      "C091":ANSI2(91),
                      "C092":ANSI2(92),
                      "C093":ANSI2(93),
                      "C094":ANSI2(94),
                      "C095":ANSI2(95),
                      "C096":ANSI2(96),
                      "C097":ANSI2(97),
                      "C098":ANSI2(98),
                      "C099":ANSI2(99),
                      "C100":ANSI2(100),
                      "C101":ANSI2(101),
                      "C102":ANSI2(102),
                      "C103":ANSI2(103),
                      "C104":ANSI2(104),
                      "C105":ANSI2(105),
                      "C106":ANSI2(106),
                      "C107":ANSI2(107),
                      "C108":ANSI2(108),
                      "C109":ANSI2(109),
                      "C110":ANSI2(110),
                      "STATUS":"",
                      "WINDOW":"",
                      "INITTERM":"",
                      "ENDTERM":"" ]),
                   "debug":
                   ([ "STATUS":"", "WINDOW":"", "INITTERM": "","ENDTERM":"" ]),
                     ]);
}

mapping query_term_info(string type) {
    return (term_info[type] ? term_info[type] : term_info["dumb"]);
}

string *query_terms() { return keys(term_info); }

int query_term_support(string str) {
    return (term_info[str] ? 1 : 0);
}
